config/routes.rb
Utube::Application.routes.draw do

  root :to => 'home#home'

  get 'access/login' => 'access#login'
  get 'access/logout' => 'access#logout'
  post 'access/attempt_login' => 'access#attempt_login'

  resources :videos, :subscriptions

  resources :channels do
    resources :videos
  end

  resources :users do
    resources :subscriptions
    resources :collections
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base

  # ASSOCIATIONS
  has_many :subscriptions
  belongs_to :user

  # VALIDATIONS

  # DEFINITIONS
  def videos
    videos = []
    subs = subscriptions
    subs.each do |subscription|
      v = subscription.channel.videos
      videos = videos + v
    end
    videos.sort!{|a,b| b.created_at <=> a.created_at}
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]


  def index
    @user = User.find(params[:user_id])
    @collections = User.find(params[:user_id]).collections
  end


  def show
    @user = User.find(params[:user_id])
    @collection = Collection.find(params[:id])
  end


  def new
    @user = User.find(params[:user_id])
    @collection = User.find(params[:user_id]).collections.new
  end


  def edit
    @user = User.find(params[:user_id])
  end


  def create
    @collection = @user.collections.new(collection_params)
      if @collection.save
        redirect_to user_collections_path(@user), notice: 'Collection was successfully created.'
      else
        render action: 'new'
      end
  end


  def update
    params[:collection][:subscription_ids] ||= []
    @user = User.find(params[:user_id])
      if @collection.update(collection_params)
        redirect_to user_collection_path(@user, @collection), notice: 'Collection was successfully updated.'
      else
        render action: 'edit'

      end
  end

  def destroy
    @user = User.find(params[:user_id])
    @collection.destroy
    redirect_to user_collections_path(@user)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for [@user, @collection] do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% @collection.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Subscriptions
    <% @user.subscriptions_all.each do |subscription| %>
      <div>
        <%= f.label subscription.channel_name %>
        <%= hidden_field_tag 'collection[subscription_ids][]' %>
        <%= check_box_tag 'collection[subscription_ids][]', subscription.id, @collection.subscriptions.include?(subscription) %>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', user_collection_path(@user, @collection) %> |
<%= link_to 'Delete', '#' %> |
<%= link_to 'Back', user_collection_path(@user, @collection) %>

app/views/collections/index.html.erb
<% if @user %>

  <div id="left-sidebar" class="leftfloat sidebar">
    <ul class="sidebar-list">
      <li><%= link_to @user.name, channel_path(@user.channel), :id => 'username' %></li>
      <li><%= link_to 'What to see', root_path %></li>
      <li><%= link_to "My Subscriptions", user_subscriptions_path(@user) %></li>
      <li><%= link_to 'Watch Later', '#' %>  </li>
    </ul>


    <hr>

    <h4>SUBSCRIPTIONS</h4>
    <ul class="sidebar-list">
      <% @user.collections.each do |collection| %>
        <li><%= link_to collection.name, user_collection_path(@user, collection) %></li>
      <% end %>
      <% @user.subscriptions_all.each do |subscription| %>
        <li><%= link_to subscription.channel_name, channel_path(subscription.channel) %></li>
      <% end %>
    </ul>


    <hr>
    <ul id="manage-collections" class="sidebar-list">
      <li class="selected"><div class="ico"></div>

      Manage Collections</li>
    </ul>
  </div>

  <div id="main" class="leftfloat">

    <% @user.subscriptions_all.each do |subscription| %>

    <% end %>

  </div>

  <div id="right-sidebar" class="leftfloat"></div>


<% else %>

  <div id="left-sidebar" class="leftfloat sidebar">

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla

    <hr>

    <h4>
      Channels
    </h4>

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla


  </div>

  <div id="main" class="leftfloat">

  </div>

  <div id="right-sidebar" class="leftfloat"></div>


<% end %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', user_collections_path(@user) %>

app/views/collections/show.html.erb
<% if @user %>

  <div id="left-sidebar" class="leftfloat sidebar">
    <ul class="sidebar-list">
      <li><%= link_to @user.name, channel_path(@user.channel), :id => 'username' %></li>
      <li><%= link_to 'What to see', root_path %></li>
      <li><%= link_to "My Subscriptions", user_subscriptions_path(@user) %></li>
      <li><%= link_to 'Watch Later', '#' %>  </li>
    </ul>


    <hr>

    <h4>SUBSCRIPTIONS</h4>
    <ul class="sidebar-list">

      <% @user.collections.each do |collection|%>
        <% if collection.id == params[:id] %>
          stuff
          <li class="selected"><%= collection.name %></li>
        <% else %>
          <li><%= link_to collection.name, user_collection_path(@user, collection) %></li>
        <% end %>
      <% end %>

      <% @user.subscriptions_all.each do |subscription| %>
        <li><%= link_to subscription.channel_name, channel_path(subscription.channel) %></li>
      <% end %>
    </ul>


    <hr>
    <div id="manage-collections">
      <div class="ico"></div>
      <%= link_to image_tag('icon-04.png', alt: 'logo'), user_collections_path(@user), :class => 'icon' %>
      <%= link_to 'Manage subscriptions', user_collections_path(@user) %>
    </div>
  </div>





  <div id="main" class="leftfloat">

    <h1><%= @collection.name %></h1>
    <div class="options"> <%= link_to 'Manage Collection', edit_user_collection_path(@user, @collection) %> </div>
    <hr>
    <h2>Channels subscribed</h2>
    <% @collection.subscriptions.each do |subscription| %>
      <div><%= subscription.channel_name %></div>
    <% end %>
    <hr>

    <h2>Last uploads</h2>
    <% @collection.videos.each do |video| %>
      <div><%= video.title %></div>
    <% end %>
  </div>

  <div id="right-sidebar" class="leftfloat"></div>


<% else %>

  <div id="left-sidebar" class="leftfloat sidebar">

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla

    <hr>

    <h4>
      Channels
    </h4>

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla


  </div>

  <div id="main" class="leftfloat">

  </div>

  <div id="right-sidebar" class="leftfloat"></div>


<% end %>





<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @collection.user_id %>
</p>

<%= link_to 'Edit', edit_user_collection_path(@user, @collection) %> |