config/routes.rb
Utube::Application.routes.draw do

  root :to => 'home#home'

  get 'access/login' => 'access#login'
  get 'access/logout' => 'access#logout'
  post 'access/attempt_login' => 'access#attempt_login'

  resources :videos, :subscriptions

  resources :channels do
    resources :videos
  end

  resources :users do
    resources :subscriptions
    resources :collections
  end

end

app/models/video.rb
class Video < ActiveRecord::Base

  # ASSOCIATIONS
  belongs_to :channel


  # VALIDATIONS

  # DEFINITIONS

  def owner
    channel.user
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_action :set_video, only: [:show]


  def show
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
    # @video = Video.find(params[:id])    ---> set_video
  end




  ## Rails stuff... Not sure what to do about it.

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:channel_id, :title, :embbeded)
    end



end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/show.html.erb
<% if @user %>

  <div id="left-sidebar" class="leftfloat sidebar">
    <ul class="sidebar-list">
      <li><%= link_to @user.name, channel_path(@user.channel) , :id => 'username' %></li>
      <li><%= link_to 'What to see', root_path  %></li>
      <li><%= link_to "My Subscriptions", user_subscriptions_path(@user) %></li>
      <li><%= link_to 'Watch Later', '#' %>  </li>
    </ul>


    <hr>

    <h4>SUBSCRIPTIONS</h4>
    <ul class="sidebar-list">
      <% @user.collections.each do |collection| %>
        <li><%= link_to collection.name, user_collection_path(@user, collection)  %></li>
      <% end %>
      <% @user.subscriptions_all.each do |subscription| %>
        <li><%= link_to subscription.channel_name, channel_path(subscription.channel)  %></li>
      <% end %>
    </ul>



    <hr>
    <div id="manage-collections">
      <div class="ico"></div>
      <%=  link_to image_tag('icon-04.png', alt: 'logo'), user_collections_path(@user), :class => 'icon' %>
      <%=  link_to 'Manage subscriptions', user_collections_path(@user) %>
    </div>
  </div>

  <div id="video-show" class="leftfloat">
    <div id="video"><%= @video.embbeded.html_safe %></div>

    <div id="video-info-container">
      <div id="video-title"><%= @video.title %></div>
      <div id="channel-info-container">
        <div id="channel-avatar"><%= image_tag('icon-05.png', alt: 'avatar') %></div>
        <div id="channel-info">
          <div id="channel-owner"><%= @video.owner.name %></div>
          <div id="channel-subscribe" class="button"> Subscribe</div>
        </div>
      </div>

    </div>


  </div>

  <div id="right-sidebar" class="leftfloat">
    <div class="recommended-video">

    </div>
    <div class="recommended-video">

    </div>
    <div class="recommended-video">

    </div>
    <div class="recommended-video">

    </div>
    <div class="recommended-video">

    </div>
    <div class="recommended-video">

    </div>
    <div class="recommended-video">

    </div>
  </div>


<% else %>

  <div id="left-sidebar" class="leftfloat sidebar">

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla

    <hr>

    <h4>
      Channels
    </h4>

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla


  </div>

  <div id="video-show" class="leftfloat">
    <%= @video.embbeded.html_safe %>
  </div>

  <div id="right-sidebar" class="leftfloat"></div>


<% end %>