config/routes.rb
Utube::Application.routes.draw do

  root :to => 'home#home'

  get 'access/login' => 'access#login'
  get 'access/logout' => 'access#logout'
  post 'access/attempt_login' => 'access#attempt_login'

  resources :videos, :subscriptions

  resources :channels do
    resources :videos
  end

  resources :users do
    resources :subscriptions
    resources :collections
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  # ASSOCIATIONS
  belongs_to :collection
  belongs_to :channel

  # VALIDATIONS

  # DEFINITIONS

  def channel_name
     channel.user.name
  end

  def videos
    channel.videos
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    if session[:user_id]
      @user = User.find(session[:user_id])
      @subscriptions = Subscription.all
    else
      @subscriptions = []
    end

  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subscription }
      else
        format.html { render action: 'new' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:user_id, :channel_id, :collection_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.erb
<% if @user %>

  <div id="left-sidebar" class="leftfloat sidebar">
    <ul class="sidebar-list">
      <li><%= link_to @user.name, channel_path(@user.channel) , :id => 'username' %></li>
      <li><%= link_to 'What to see', root_path %></li>
      <li class='selected'>My Subscriptions</li>
      <li><%= link_to 'Watch Later', '#' %>  </li>
    </ul>


    <hr>

    <h4>SUBSCRIPTIONS</h4>
    <ul class="sidebar-list">
      <% @user.collections.each do |collection| %>
        <li><%= link_to collection.name, user_collection_path(@user, collection)  %></li>
      <% end %>
      <% @user.subscriptions_all.each do |subscription| %>
        <li><%= link_to subscription.channel_name, channel_path(subscription.channel)  %></li>
      <% end %>
    </ul>



    <hr>
    <div id="manage-collections">
      <div class="ico"></div>
      <%=  link_to image_tag('icon-04.png', alt: 'logo'), user_collections_path(@user), :class => 'icon' %>
      <%=  link_to 'Manage subscriptions', user_collections_path(@user) %>
    </div>
  </div>

  <div id="main" class="leftfloat">
    <% @user.subscriptions_videos.each do |video| %>

    <div>
      <div><%= link_to video.owner.name, channel_path(video.channel) %> uploaded a video</div>
      <div><%= link_to video.title, video_path(video) %></div>
      <hr>
    </div>
    <% end %>



  </div>

  <div id="right-sidebar" class="leftfloat"></div>


<% else %>

  <div id="left-sidebar" class="leftfloat sidebar">

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla

    <hr>

    <h4>
      Channels
    </h4>

    bla bla bla bla
    bla bla bla bla
    bla bla bla bla
    bla bla bla bla


  </div>

  <div id="main" class="leftfloat">

  </div>

  <div id="right-sidebar" class="leftfloat"></div>


<% end %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @subscription.user_id %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @subscription.channel_id %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @subscription.collection_id %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>